name: Bump Version on PR Merge to Develop

on:
  pull_request:
    types: [closed]
    branches:
      - develop

permissions:
  contents: write

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0

      - name: Decide version bump type
        run: |
          HEAD_REF="${{ github.event.pull_request.head.ref }}"
          VERSION=$(node -p "require('./package.json').version")
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          if [[ "$HEAD_REF" == feature/* ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
            TYPE="minor"
          else
            PATCH=$((PATCH + 1))
            TYPE="patch"
          fi

          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "BUMP_TYPE=$TYPE" >> $GITHUB_ENV

          jq --arg v "$NEW_VERSION" '.version = $v' package.json > tmp && mv tmp package.json

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json
          git commit -m "chore: bump ${{ env.BUMP_TYPE }} version to ${{ env.NEW_VERSION }}"
          git push

      - name: Tag current version and push the tag
        run: |
          VERSION="${{ env.NEW_VERSION }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v$VERSION
          git push origin v$VERSION
