name: Tag Version on Merge to Master

on:
  pull_request:
    types: [closed]
    branches:
      - master

permissions:
  contents: write

jobs:
  tag-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0

      - name: Tag current version and push the tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v$VERSION
          git push origin v$VERSION
